global:
  # The global scrape interval is a good default for most metrics.
  scrape_interval: 15s

scrape_configs:
  
  # This job scrapes the JMX Exporter on all Kafka broker containers.
  - job_name: 'kafka'
    # Use static_configs to list each broker's hostname and JMX Exporter port.
    static_configs:
      - targets: ['kafka1:8181', 'kafka2:8182', 'kafka3:8183']
